### ISSUE TITLE
Support `postinstall` script

### ISSUE THREAD

**Issue by bycruz** [DvvCz/cpkg#14]
Analogous to npm postinstall scripts.

Would make it just that much easier to have dependencies with their own build steps.

Ie for building raylib as a git dependency:

```toml
[scripts]
postinstall = "cd target/vendor/raylib/src && make PLATFORM=PLATFORM_DESKTOP USE_WAYLAND_DISPLAY=TRUE"
```
